# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1auuYMSNm_I7ww1DooIRYdsvO-nnj21B_
"""

from selenium import webdriver
import time

driver = webdriver.Chrome(executable_path='path/to/chromedriver.exe')


def test_sample_case():

    driver.get("https://www.facebook.com/")


    driver.find_element_by_link_text("Login").click()
    driver.find_element_by_id("username").send_keys("yourUsername")
    driver.find_element_by_id("password").send_keys("yourPassword")
    driver.find_element_by_id("loginButton").click()

test_sample_case()